### PR TITLE
Drivers extensible through configuration

### PR DESCRIPTION
**Pull request by Norgul**
Hello, 

I've modified the code to provide truly extensible code with configuration which I deem is simpler than overriding complete classes and re-binding them. 

Some of the changes are also due to what I consider misleading nomenclature, but you will find those changes are not so drastic. 

I've also added readme for extending.

Keep up the good work, and hit me back if something else is needed.

Regards

### CODE REVIEW

**Comment by Norgul** [comment]
Also, I see `fallback` and `catchAll` routes as two same methods. I'd leave only `fallback`. Thoughts?

**Comment by Norgul** [comment]
@mpociot I have some additional ideas for the package which I'd like to implement. We can discuss it over here or you can contact me on marko.dupor@gmail.com. If you don't have time for reviewing, I will stop submitting PR's and just keep a fork. 

Thanks
Keep up the good work

**Comment by mpociot** [comment]
Hi @Norgul 
Thank you for the PR.
`catchAll` and `fallback` behave differently.
The `catchAll` method catches every incoming email - even if it gets caught by a different route. The `fallback` method will only be called when no other route matches - which is a slightly different feature.

**Comment by Norgul** [comment]
@mpociot gotcha. 

I made some significant changes on another branch which I found really useful for my use case. It changes the concept slightly, however it introduces some fun features. I will submit them as another PR so feel free to take a look. If you find them helpful as well and would like to merge, I will support those with tests and additional readme. 

Stay tuned.

**Pull request closed without merging**
