### PR TITLE
Laravel 5.8 support

### PR DESCRIPTION
**Pull request by radmen**
I need this package in a project I'm working on.
Since there's no (yet) support for Laravel 5.8 I decided to make one :)

In this PR I've just bumped package versions. This (+simple fix in a test case) was enough to make the tests pass.

I have to admit that I didn't test this on a real Laravel installation.

### CODE REVIEW

**Comment by affektde** [comment]
merge? <3 

or is this not sufficient?

**Comment by RosiersRobin** [comment]
Please merge

**Comment by radmen** [comment]
@mpociot fixed in 8abfc2a

**Comment by snellingio** [comment]
@mpociot hope you had a great vacation! Just going to ping you on this to merge when you get a chance.

**Pull request merged**
