### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by Norgul**
Hello @mpociot, as promised, here comes the big change PR. Take a look and feel free to comment. Independently of the outcome, I will continue to support my version since I need it anyways. I understand if this is too much of a change to accept, and that is fine as well. Thanks in advance.

# Change log

## Concept

The main entity is a `MailboxGroup`. What it enables you to do is to have multiple `Mailboxes`, each with its own set of patterns and actions to execute. 

Refactor has been done so that `Mailbox` provides a fluent API to define same set of features as before with some nice additions. 

Example:

```php
$mailbox = new Mailbox();

$mailbox
    ->from('{user}@gmail.com')
    ->to('{user2}@gmail.com')
    ->subject('Subject to match')
    ->where('user', '.*')
    ->where('user2', '.*')
    ->action(function (InboundEmail $email) {
        Log::info("Mail received");
    })
    ->matchEither()
    ->priority(10);

```
The concept now is that each mailbox has a single or multiple rules it can match, however it can have only one action to execute. Reason being to enable matching all or either of the rules imposed. 

By default, all patterns need to be matched in order for action to be executed. So if you provide `from` and `to`, they both need to match. This can be changed by including a `matchEither()` function which will transform this logic to matching at least one. 

Due to the fact that multiple mailboxes can exist now, `MailboxGroup` is responsible for running them. Executing `MailboxGroup::run($email)` will run all the mailboxes, but will before order them by given `priority()`. `Mailbox` has a default priority of `0`. The bigger the number, the sooner it is executed. 

Group example:
```php
$group = new MailboxGroup(); 

$group
    ->add($mailbox)
    ->add($mailbox2)
    ->add($mailbox3) 
    ->fallback(function (InboundEmail $email) {
        Log::info("Fell back");
    })
    ->continuousMatching()
    ->run($email);
```

You are responsible for adding mailboxes to the group (be it in the service provider or the controller itself). Fallback is pulled out to `MailboxGroup` for logical reasons. If none of the mailboxes match, fallback will be executed. A new feature here is that mailboxes will, by default, stop at first match. Meaning, if out of 5 mailboxes, second one matches the incoming mail, execution will stop. This can be overridden including the `continuousMatching()` function which will run through all mailboxes. So if match is found in 3/5 mailboxes, those 3 callbacks will be executed. 

## Dependencies

PHP version has been bumped to `7.4`. Breaking changes are introduced, `7.3` is no longer supported, and in the next few days I will complete all type hints and return types, together with strict modes included.

Support for `6.x` Laravel has been dropped. `composer install` requires a ton of memory with it, breaking most of the times if you don't give more memory to it. This is also the reason Scrutinizer checks break. 

## Drivers

I have removed drivers all together. Reason being that they were (at least for me) ambiguous, and their only purpose was exposing routes behind the scenes. Current setup also doesn't limit you in using a single driver. 

I like my code to be explicit, so currently in order to set up the package you need to:

1. Set up endpoint manually (I like single action controllers for these purposes, but not mandatory):

```php
Route::post('receive', ReceiveEmailController::class);
```

2. Add a `MailboxRequest` form request validation, or extend it if needed.

```php
public function __invoke(MailboxRequest $request)
{
    ...
}
```

3. Define mailboxes and run them:

```php
public function __invoke(MailboxRequest $request)
{
    $mailbox = (new Mailbox())->from(...)->action(...);

    MailboxGroup::add($mailbox);
    MailboxGroup::run($request->email());
}
```

4. Alternatively, you can define mailboxes in your service provider boot method, leaving the controller clean:

```php
// App service provider
public function boot()
{
    $mailbox = (new Mailbox())->from(...)->action(...);

    MailboxGroup::add($mailbox);
}

// Controller
public function __invoke(MailboxRequest $request)
{
    MailboxGroup::run($request->email());
}
```

5. Alternatively, option I prefer is to pull out mailbox definition to a separate class and include it within the controller so that it doesn't overburden the rest of API calls.

```php
public function __invoke(MailboxRequest $request)
{
    // Factory leading to defining mailboxes, and ultimately running them.
    MailboxService::receiveEmail($request->email());
}
```

6.. Controllers being used as driver callbacks are still there for your convenience, so you can point the routes to different variants of those:

```php
Route::post('receive/mailgun', MailgunController::class);
Route::post('receive/mailcare', MailCareController::class);
Route::post('receive/postmark', PostmarkController::class);
Route::post('receive/sendgrid', SendGridController::class);
```

## Dev naming

Some concepts, variables etc. have been renamed to be more intuitive. 

## Tests

Tests which made sense were modified to pass, other were deleted as things like `Route` and `RouteCollection` no longer exist. I am willing to support new features with tests. 

## Readme

I think readme is a tad outdated and unnecessarily long. I will probably rewrite it.

### CODE REVIEW

**Comment by mfn** [comment]
This is, like, not even a fork, but a new package 😅

**Comment by Norgul** [comment]
@mfn yes and no :D A lot of code is reused, and bottom concept is the same, you hit an endpoint and traverse the registered patterns.

Also I'd suggest to transfer mailbox registration to a controller instead of a service provider. We for one have a large contact centre which will need to use large set of patterns and be able to have them configurable. I'd rather if that isn't part of initialization for each endpoint hit, but rather to do that on the go when the mail is received.

**Comment by vesper8** [comment]
@Norgul First of all thanks a lot for submitting this awesome PR. I love @mpociot offerings and I love it even more with users like you take it upon themselves to modernize, extend and enhance in order to keep the offering relevant and up-to-date. I will definitely be using your fork until this PR is accepted

Now, not to want to hijack your thread but I was hoping you could clarify something for me because I remain confused as to whether this is something this package can achieve out-of-the-box. I keep seeing references to `@gmail.com` addresses in the examples, including in your own example above. But is it even possible to use `laravel-mailbox` to intercept and parse `@gmail.com` addresses?

Is it also possible to have `laravel-mailbox` periodically check for new mail in regular SMTP accounts, without using Mailgun/Postmark/Sendgrid/MailCare I mean. Can `laravel-mailbox` connect directly like a regular email client would and check for new emails. Or does it only work with a middleman mail provider that supports routes/webhooks?

I've been frustrated with setting up this package on a new project because it seems like none of the supported drivers offer webhooks in their free tier (Mailgun used to be free and now charges 35$/month for their incoming webhook "routes" functionality).

And a new client of mine wants me to set up a service that can parse his incoming email into a database and he's using a generic cpanel mailbox so I want to know can I just simply use his imap/smtp credentials with `laravel-mailbox` or I absolutely need to use one of the supported drivers?

Would very much appreciate an answer if you have time. Thank you very much

**Comment by Norgul** [comment]
Hello @vesper8. By all means, ask away and thank you for the nice comments :).

Regarding the gmail examples, those are not limiting at all. Let me try to clarify:

Ex1. exact match: `from('your.mail@gmail.com')` - meaning that only mails exactly coming from `your.mail@gmail.com` will be matched.
Ex2. partial match: `from('{pattern}@gmail.com')` - meaning any gmail address matching the name pattern will be matched (i.e. if pattern allows only characters, `someone@gmail.com` and `someoneelse@gmail.com` will be matched, but `newmail123@gmail` wont).
Ex3. partial match: `from('your.name@{provider}')` - same as ex2, but this time name is fixed, but provider is flexible. Having pattern enabling anything (`.*`), valid matching mails would be `your.name@gmail.com`, `your.name@yahoo.com` as well as `your.name@completely.random.provider.com`.
Ex4. full regex match: `from('{pattern}')` - mostly the same as previous two example, but now you can control the exact pattern. 

Note that ex2, 3 and 4 require you to clarify which pattern is allowed for the specific match. 

Having `from('{pattern}@gmail.com')` requires for example `where('pattern', '[A-Z]+')` 
Having `from('your.name@{provider}')` requires for example `where('provider', 'yahoo.*')`

So any keyword between `{ }` has to have its own defined `where()` defining which pattern needs to be matched for that specific keyword. 

Regarding incoming mail, this is something which needs to be done manually as it is not in the Laravel scope to do so. What I've done is installed procmail on server and have the script catch incoming mails and automatically posting them on my endpoint. I am not using any of the drivers (and frankly I find them more confusing than useful, I'd rather refactor that part as well), but instead defining my own endpoint which is then hit on incoming mails.

**Comment by Norgul** [comment]
@mpociot @vesper8 - I suppose this is too big of a PR to be accepted, and that's fine :) I will be creating a new package so I can improve it further and avoid referencing my fork in composer packages since I have some issues with it. I will give credits and link here for the original idea. I hope that's okay.

**Comment by vesper8** [comment]
@Norgul A similar thing happened on the laravel-websockets package where there was a highly valuable big PR that wasn't getting any love.. and what ended up working in the end was that someone asked to become a contributor and took on the work of improving / merging and as a result the laravel-websockets has seen a huge improvement. So maybe you should ask @mpociot if you could become an official contributor/maintainer. It sure would be nice to see your improvements be added to this package which already has a lot of visibility/usage

**Comment by Norgul** [comment]
I have an idea to reformat the package for incoming communication, regardless of whether this is email or some other service. I don't know if it is in this package roadmap...and if that happens `mailbox` isn't exactly the right naming then. I will keep you posted

**Pull request closed without merging**
